<<<<<<< Updated upstream
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        //实例化 Promise 对象
        //Promise对象有两个属性，一个属性来表示它的状态，一个是状态对应执行的值
        const p = new Promise(function (resolve, reject) {
            setTimeout(function () {
                let data = "数据读取成功";
                //设置 p 对象的状态为成功，并设置成功的值
                resolve(data);

                let err = "数据读取失败";
                //设置 p 对象的状态为失败，并设置失败的值
                // reject(err);
            }, 1000);
        });

        //调用 Promise 对象的 then 方法  可以链式调用
        //返回状态(PromiseState)有两个: fulfilled(resolved)和rejected
        const result = p.then(function (value) {
            console.log(value);

            //1.非Promise类型的属性
            return '非promise类型';

            //2.是 Promise 对象
            // return new Promise((resolve, reject) => {
            //     resolve('ok');
            //     reject('error');
            // });

            //3.抛出错误
            // throw new Error('出错了');
            // throw '出错了';

        }, function (reason) {
            console.log(reason);
        });


        console.log("-----------1111111111111-----------");
        //then方法的返回结果是 Promise 对象，对象状态由回调函数的执行结果决定，
        //1. 如果回调函数中返回的结果是 非Promise 类型的属性，状态为成功，返回值为对象的成功的值
        // console.log(result);


        //async函数 (Promise对象的语法糖)
        async function fn() {

            //1.返回的结果是一个非 Promise 类型的对象，返回的结果就是成功的 Promise 对象
            // return '返回一个非 Promise 类型的对象';

            // //2.抛出错误，返回的结果就是一个失败的 Promise
            // throw new Error('抛出s错误');

            // //3.返回的结果是一个 Promise 对象
            return new Promise((resolve, reject) => {
                // resolve('返回resolve');
                reject('返回reject');
            });
        }

        const result1 = fn();
        console.log(result1);

        //调用 then 方法
        result1.then(value => {
            console.log(value);
        }, reason => {
            console.warn(reason);
        })
        console.log(result1);


        //await表达式   必须放在async函数中
        //创建 Promise 对象
        const p1 = new Promise((resolve, reject) => {
            resolve('成功了');
            // reject('失败了');
        });

        async function fn1() {
            try {
                let result2 = await p1;
                console.log(result2);
            } catch (e) {
                console.log(e);
            }
        }
        fn1();

        const p1 = new Promise(function (resolve, reject) {
            Promise.all([
                new Promise((r, j) => j()),
                new Promise((r) => r(3)).then(console.log)
            ]);
        });
        p1.then(function (val) {
            console.log("成功了");
        }, function (reason) {
            console.log("失败了");
        });



    </script>
</body>

=======
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        //实例化 Promise 对象
        //Promise对象有两个属性，一个属性来表示它的状态，一个是状态对应执行的值
        const p = new Promise(function (resolve, reject) {
            setTimeout(function () {
                let data = "数据读取成功";
                //设置 p 对象的状态为成功，并设置成功的值
                // resolve(data);

                let err = "数据读取失败";
                //设置 p 对象的状态为失败，并设置失败的值
                reject(err);
            }, 1000);
        });

        //调用 Promise 对象的 then 方法  可以链式调用
        //返回状态(PromiseState)有两个: fulfilled(resolved)和rejected
        p.then(function (value) {
            console.log(value);

            //1.非Promise类型的属性
            return '非promise类型';

            //2.是 Promise 对象
            // return new Promise((resolve, reject) => {
            //     resolve('ok');
            //     reject('error');
            // });

            //3.抛出错误
            // throw new Error('出错了');
            // throw '出错了';

        }, function (reason) {
            console.log(reason);
        });


        console.log("-----------1111111111111-----------");
        //then方法的返回结果是 Promise 对象，对象状态由回调函数的执行结果决定，
        //1. 如果回调函数中返回的结果是 非Promise 类型的属性，状态为成功，返回值为对象的成功的值
        // console.log(result);


        //async函数 (Promise对象的语法糖)
        async function fn() {

            //1.返回的结果是一个非 Promise 类型的对象，返回的结果就是成功的 Promise 对象
            // return '返回一个非 Promise 类型的对象';

            // //2.抛出错误，返回的结果就是一个失败的 Promise
            // throw new Error('抛出s错误');

            // //3.返回的结果是一个 Promise 对象
            return new Promise((resolve, reject) => {
                // resolve('返回resolve');
                reject('返回reject');
            });
        }

        const result1 = fn();
        console.log(result1);

        //调用 then 方法
        result1.then(value => {
            console.log(value);
        }, reason => {
            console.warn(reason);
        })
        console.log(result1);


        //await表达式   必须放在async函数中
        //创建 Promise 对象
        const p1 = new Promise((resolve, reject) => {
            resolve('成功了');
            // reject('失败了');
        });

        async function fn1() {
            try {
                let result2 = await p1;
                console.log(result2);
            } catch (e) {
                console.log(e);
            }
        }
        fn1();

        const p2 = new Promise(function (resolve, reject) {
            Promise.all([
                new Promise((r, j) => j()),
                new Promise((r) => r(3)).then(console.log)
            ]);
        });
        p2.then(function (val) {
            console.log("成功了");
        }, function (reason) {
            console.log("失败了");
        });



    </script>
</body>

>>>>>>> Stashed changes
</html>